# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e792205edbb2bfaa9ceaa761b725f163298bc31583eedc4eac987af61e71e8c7a0b042de58edcb9d131964a4d32540f537f99429f7664d384e395e0ac8c64d12

test:
  secret_key_base: 2dd60e09380e01fb0d63affc7bc9fd62e0f12f16a9f43097d64d1aec49f4fc6f5083f22710b17e63786a1f8727efc180dfbb7097aa79a63336d2e7da4f39c433

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
